version: "3.8"

services:
  userservice:
    build: ./userservice
    container_name: userservice
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=default

  greetingservice:
    build: ./greetingservice
    container_name: greetingservice
    ports:
      - "8082:8082"
    depends_on:
      - userservice
    environment:
      - SPRING_PROFILES_ACTIVE=default
